### ISSUE TITLE
Błąd parsowania wyników

### ISSUE THREAD

**Issue by peetereczek** [peetereczek/ztm#10]
Wyniki odpowiedzi na zapytanie nie są parsowane do sensora

```log
Update for sensor.ztm_217_from_3309_02 failsTraceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update await self.async_update()
File "/config/custom_components/ztm/sensor.py", line 139, in async_update self._timetable = self.map_results(res.get('response', []))
File "/config/custom_components/ztm/sensor.py", line 212, in map_results return [parse_raw_timetable(row) for row in response['result']]
File "/config/custom_components/ztm/sensor.py", line 212, in <listcomp> return [parse_raw_timetable(row) for row in response['result']]
File "/config/custom_components/ztm/sensor.py", line 218, in parse_raw_timetable for val in raw_result['values']:
TypeError: string indices must be integers
```

**Comment by peetereczek** [comment]
API odpowiedział błędem:

```log
2020-02-07 09:38:35 DEBUG (MainThread) [custom_components.ztm.sensor] API RESPONSE: {'response': {'result': 'Błędna metoda lub parametry wywołania'}}
```

Wygląda jakby Warszawskie API nie działało

**Comment by peetereczek** [comment]
Od 06 lutego 2020 godzina 22:56 API nie zwraca wartości po zapytaniu GET

**Comment by peetereczek** [comment]
Na przyszłość jeżeli API nie będzie działało, najlepiej napisać maila bezpośrednio do specjalistów w UM Warszawa:

Skibiński Cyryl <cskibinski@um.warszawa.pl>
Kunicki Robert <rkunicki@um.warszawa.pl>

Po kontakcie mailowym, API wróciło do życia

**Comment by marekkrukowski** [comment]
Czy ta integracja jeszcze działa? Od dłuższego czasu nie pobiera mi danych.
Myślałem, że może kod api wygasł i wygenerowałem ponownie, ale nadal nic.
