### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by peetereczek** [peetereczek/ztm#9]
Po ostatnim updacie (0.2.0) zaczęło sypać mi błędami:
Cannot connect to ZTM API endpoint.
Sprawdziłem klucz i po stronie API wszystko wygląda OK.
Zapewne w wyniku czego, pojawia się błąd odczytu:
```txt
Update for sensor.ztm_xxx_from_xxxx_xx fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
await self.async_update()
File "/config/custom_components/ztm/sensor.py", line 136, in async_update
if res.get('error', ''):
AttributeError: 'NoneType' object has no attribute 'get'
```
Powrót do 0.1.3 usuwa problem.

**Comment by peetereczek** [comment]
Błąd wynikał ze starej konfiguracji karty korzystającej z sensora w wersji 0.1.3
Wersja 0.2.0 zmienia nazwenictwo sensorów ztm w HA
